
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UMINUS = 5;
  public static final int ADD_OPERATOR = 24;
  public static final int CASE = 36;
  public static final int INTEGER = 12;
  public static final int FOR = 34;
  public static final int MINUS = 4;
  public static final int WRITE = 15;
  public static final int END_PROGRAM = 9;
  public static final int NOT = 26;
  public static final int RPAR = 3;
  public static final int SEPARATOR = 29;
  public static final int BEGIN = 14;
  public static final int ASSIGN = 22;
  public static final int IF = 17;
  public static final int RELOP = 23;
  public static final int EOF = 0;
  public static final int BOOLEAN = 13;
  public static final int TRUE = 27;
  public static final int error = 1;
  public static final int PROGRAM = 6;
  public static final int CHARACTER_CONSTANT = 33;
  public static final int BREAK = 39;
  public static final int SWITCH = 37;
  public static final int INSTRUCTION_SEPARATOR = 8;
  public static final int COLON = 35;
  public static final int ELSE = 30;
  public static final int STRING_CONSTANT = 32;
  public static final int MULT_OPERATOR = 25;
  public static final int READ = 16;
  public static final int WHILE = 19;
  public static final int DEFAULT = 38;
  public static final int THEN = 18;
  public static final int END = 21;
  public static final int LPAR = 2;
  public static final int FALSE = 28;
  public static final int VAR = 10;
  public static final int PROCEDURE = 11;
  public static final int DO = 20;
  public static final int INTEGER_CONSTANT = 31;
  public static final int IDENTIFIER = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAR",
  "RPAR",
  "MINUS",
  "UMINUS",
  "PROGRAM",
  "IDENTIFIER",
  "INSTRUCTION_SEPARATOR",
  "END_PROGRAM",
  "VAR",
  "PROCEDURE",
  "INTEGER",
  "BOOLEAN",
  "BEGIN",
  "WRITE",
  "READ",
  "IF",
  "THEN",
  "WHILE",
  "DO",
  "END",
  "ASSIGN",
  "RELOP",
  "ADD_OPERATOR",
  "MULT_OPERATOR",
  "NOT",
  "TRUE",
  "FALSE",
  "SEPARATOR",
  "ELSE",
  "INTEGER_CONSTANT",
  "STRING_CONSTANT",
  "CHARACTER_CONSTANT",
  "FOR",
  "COLON",
  "CASE",
  "SWITCH",
  "DEFAULT",
  "BREAK"
  };
}

